// Hard facts about each exam, shown next to Career Match suggestions.
// They are copied from Skylar's knowledge base (KB in pages/api/match.js) and are
// never written by the AI, so a figure cannot be invented or garbled, and the
// AI has less to write, which makes Career Match faster.
// Leave a field empty ('' or []) when the knowledge base does not state it.
// Deep Skylar will move these facts into the admin panel so they can be edited there.

const ENAFM = {
  exam_format: 'Paper 1 (3 hours): 100 MCQs, Biology 50, Chemistry 25, Physics 25. Paper 2 (1.5 hours, after a 2-hour break): 50 MCQs, General Knowledge 35, French 15.',
  key_subjects: ['Biology', 'Chemistry', 'Physics', 'General Knowledge', 'French'],
  places: '',
  centres: 'All 10 regions, same paper on the same day. The writing centre does not have to match the chosen institution.',
  fee: '20000 FCFA',
  exam_date: '',
  age_limit: 'Maximum 23 years as of 1 January of the exam year',
  eligibility: 'Bac C or D, or GCE A/L with Biology and Chemistry. GCE O/L must include Biology, Chemistry, and Physics or Mathematics in the same session.',
  registration: 'Choose one institution and one track: FMSB Yaounde I, FMSP Dschang, FMSP Douala, FHS Buea, FMSB Garoua or UdM Bangangte.',
};

const FHS_BUEA = {
  exam_format: 'Written: 100 MCQs (Biology 40, Chemistry 20, Physics 20, English 20), then an oral of about 5 minutes before a jury on the same day, after a break of about 3 hours.',
  key_subjects: ['Biology', 'Chemistry', 'Physics', 'English'],
  places: '60',
  centres: 'FHS campus, Buea (single centre)',
  fee: '20000 FCFA',
  exam_date: '',
  age_limit: '',
  eligibility: 'GCE A/L in at least 2 subjects including Biology and Chemistry, with GCE O/L in at least 5 subjects including English and Mathematics; or Bac C or D.',
  registration: 'Internal University of Buea exam, separate from ENAFM.',
};

export const CONCOURS_FACTS = {
  ENSPY: {
    exam_format: 'Sciences and Technologies track: 2 Mathematics and 2 Physics papers, 3 hours each, equal weight. Digital Arts track: Mathematics, Computer Science and General Arts.',
    key_subjects: ['Mathematics', 'Physics'],
    places: '400 (Sciences and Technologies), 30 (Digital Arts)',
    centres: 'All 10 regional capitals',
    fee: '',
    exam_date: '',
    age_limit: 'No age limit published',
    eligibility: 'Bac C, D, E or F, or GCE A/L with Further Mathematics and Physics',
    registration: 'Online at polytechnique.cm/concours',
    notes: 'Leads to the Ingenieur de Conception diploma (5-year equivalent).',
  },
  FET: {
    exam_format: 'Written only: Mathematics (coefficient 3, 3 hours) and Physics (coefficient 3, 3 hours)',
    key_subjects: ['Mathematics', 'Physics'],
    places: '470',
    centres: 'Buea, Bamenda, Douala, Yaounde',
    fee: '20000 FCFA',
    exam_date: '',
    age_limit: '',
    eligibility: 'GCE A/L in at least 2 subjects including Mathematics and Physics, or Bac C, D, E or F',
    registration: 'ubuea.cm',
    notes: 'BEng (Bac+4) and MEng (Bac+5).',
  },
  COT: {
    exam_format: 'Mathematics (coefficient 4, 3 hours), Physics (coefficient 4, 3 hours), English (coefficient 1, 1 hour). Written exam 60%, academic file 40%.',
    key_subjects: ['Mathematics', 'Physics', 'English'],
    places: '230',
    centres: 'Buea, Bamenda, Douala, Yaounde',
    fee: '20000 FCFA',
    exam_date: '',
    age_limit: '',
    eligibility: 'GCE O/L in 5 subjects including English, Mathematics and Physics, plus GCE A/L in at least 2 including Mathematics and Physics; or Bac C, D, E, F1, F2 or F3; or GCE Technical',
    registration: '',
    notes: 'Bachelor of Technology (B.Tech) in 3 years: Computer, Electrical and Electronic, Mechanical, or Mechatronics Engineering.',
  },
  ENSPD: {
    exam_format: 'Similar to ENSPY',
    key_subjects: [],
    places: '',
    centres: '',
    fee: '',
    exam_date: '',
    age_limit: '',
    eligibility: '',
    registration: '',
    notes: 'School in Douala. Telecom/ICT, Industrial Safety, Process, Civil and Chemical Engineering.',
  },
  ENAFM_Medicine: { ...ENAFM, notes: 'Biology carries the highest coefficient; Chemistry and Physics are equal. 7 years to Docteur en Medecine.' },
  ENAFM_Pharmacy: { ...ENAFM, notes: 'Chemistry carries the highest coefficient; Biology and Physics are equal.' },
  ENAFM_Dentistry: { ...ENAFM, notes: 'Biology carries the highest coefficient; Chemistry and Physics are equal.' },
  FHS_Nursing: { ...FHS_BUEA },
  FHS_MLS: { ...FHS_BUEA },
  FHS_Midwifery: { ...FHS_BUEA },
  FHS_BMS: { ...FHS_BUEA, notes: 'Coefficients: Biology 4, Chemistry 3, Physics 3. No Mathematics required.' },
  FHS_PublicHealth: { ...FHS_BUEA },
  FASA: {
    exam_format: 'Written: Biology, Mathematics, Chemistry and General Knowledge',
    key_subjects: ['Biology', 'Mathematics', 'Chemistry', 'General Knowledge'],
    places: '330 public places (Dschang and Bafia), plus 1200 through affiliated IPES institutes',
    centres: 'Bafia, Bamenda, Douala, Dschang, Maroua, Ngaoundere, Yaounde',
    fee: '',
    exam_date: '',
    age_limit: '',
    eligibility: 'Bac A, C, D or Agricultural, or GCE A/L in at least 2 science subjects',
    registration: '',
    notes: 'Leads to Ingenieur Agronome.',
  },
  FAVM: {
    exam_format: 'Biology (3 hours) and Chemistry (3 hours). Written exam 60%, academic file 40%.',
    key_subjects: ['Biology', 'Chemistry'],
    places: '300 across 9 programmes, including Veterinary Medicine (40)',
    centres: 'Buea, Bamenda, Douala, Yaounde',
    fee: '20000 FCFA',
    exam_date: '',
    age_limit: '',
    eligibility: '',
    registration: '',
    notes: '',
  },
  ESMV: {
    exam_format: 'Biology (coefficient 4, 2 hours), Physics/Chemistry (coefficient 3, 2 hours), Mathematics (coefficient 3, 2 hours), General Knowledge (coefficient 2, 2 hours). A score below 4/20 in any paper eliminates the candidate.',
    key_subjects: ['Biology', 'Physics/Chemistry', 'Mathematics', 'General Knowledge'],
    places: '100 (Veterinary Doctors), 100 (Animal Production Engineers)',
    centres: 'Ngaoundere, Buea, Dschang, Maroua, Yaounde',
    fee: '20000 FCFA',
    exam_date: '',
    age_limit: 'Maximum 26 years as of 31 December of the exam year',
    eligibility: '',
    registration: '',
    notes: '',
  },
  ENAM: {
    exam_format: 'Four divisions: Administrative, Judiciary, Financial (Customs, Tax, Treasury) and Social Affairs',
    key_subjects: [],
    places: 'Judiciary: 15 Auditeurs de Justice and 15 Greffiers. Social Affairs: 10.',
    centres: '',
    fee: '',
    exam_date: 'August to September (2026 session)',
    age_limit: '',
    eligibility: 'Administrative Cycle A: Licence. Cycle B: Bac+2. Auditeurs de Justice: Master in Law.',
    registration: 'concours.enam.cm',
    notes: '',
  },
  EMIA: {
    exam_format: '',
    key_subjects: [],
    places: '',
    centres: 'Yaounde (single centre)',
    fee: '20000 FCFA',
    exam_date: 'Usually January',
    age_limit: '18 to 23 years; candidates must be single with no dependants',
    eligibility: 'GCE A/L in 3 subjects (excluding Religious Knowledge) plus one successful year of higher education, or any Bac plus one year of higher education',
    registration: '',
    notes: '',
  },
  ENIEG: {
    exam_format: '',
    key_subjects: [],
    places: '7000 nationwide',
    centres: 'All regional capitals',
    fee: '',
    exam_date: '30 July (2026 session)',
    age_limit: '17 to 32 years as of 1 January (2026 session)',
    eligibility: 'Any Bac series or GCE A/L equivalent',
    registration: '',
    notes: '2 years of training, leading to a primary school teaching post.',
  },
};
